### ISSUE TITLE
Update DNS entries

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/iaip#1308]
- [x] "iaip.gaepd.org" currently points to our Prod server. Instead, create CNAME pointing to gaepdit.github.io (identical setup to current "dev-iaip" subdomain).
- [x] The "iaip-cx" subdomain currently points to our UAT server (10.34.149.133). Update it to point to the Prod server (10.34.148.235).
- [x] The "dev-iaip" subdomain should be removed.

**Comment by tom-karasch** [comment]
All entries added, changed and removed.

**Comment by tom-karasch** [comment]
Sorry, didn't mean to close it on you, Doug.

**Comment by dougwaldron** [comment]
Thanks. Looks good.
